/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pizzaria.tela;

import br.com.pizzaria.entidade.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author maria.sousa9
 */
public class Principal extends javax.swing.JFrame {
    
    private Usuario usuarioLogado;
    
    public Principal() {
        initComponents();
    }
    
    public Principal(Usuario usuario) {
        initComponents();
        usuarioLogado = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        titulo = new javax.swing.JLabel();
        pizza = new javax.swing.JLabel();
        pesquisar = new javax.swing.JLabel();
        pesCliente = new javax.swing.JLabel();
        pesFornecedor = new javax.swing.JLabel();
        pesUsuario = new javax.swing.JLabel();
        cadastrar = new javax.swing.JLabel();
        cadCliente1 = new javax.swing.JLabel();
        cadFornecedor1 = new javax.swing.JLabel();
        cadFornecedor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuBarra = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        clienteCadastro = new javax.swing.JMenuItem();
        UsuarioCadastro = new javax.swing.JMenuItem();
        FornecedorCadastro = new javax.swing.JMenuItem();
        pesquisa = new javax.swing.JMenu();
        clientePesquisado = new javax.swing.JMenuItem();
        usuarioPesquisado = new javax.swing.JMenuItem();
        fornecedorPesquisado = new javax.swing.JMenuItem();
        pedido = new javax.swing.JMenu();
        varSair = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gupy Sistemas - Tela principal");
        setResizable(false);

        titulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("© 2022 Todos os Direitos Reservados | Gupy Sistemas");

        pizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagens/pizza.jpg"))); // NOI18N

        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagens/pesquisar.png"))); // NOI18N

        pesCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagens/pesCliente.png"))); // NOI18N
        pesCliente.setToolTipText("Abrir Pesquisa de Cliente");
        pesCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesClienteMouseClicked(evt);
            }
        });

        pesFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagens/pesFornecedor.png"))); // NOI18N
        pesFornecedor.setToolTipText("Abrir Pesquisa de Fornecedor");
        pesFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesFornecedorMouseClicked(evt);
            }
        });

        pesUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagens/pesUsuario.png"))); // NOI18N
        pesUsuario.setToolTipText("Abrir Pesquisa de Usuário");
        pesUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesUsuarioMouseClicked(evt);
            }
        });

        cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagens/cadastrar.png"))); // NOI18N

        cadCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagens/cadCliente.png"))); // NOI18N
        cadCliente1.setToolTipText("Abrir Cadastro de Cliente");
        cadCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadCliente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadCliente1MouseClicked(evt);
            }
        });

        cadFornecedor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagens/cadFornecedor.png"))); // NOI18N
        cadFornecedor1.setToolTipText("Abrir Cadastro de Fornecedor");
        cadFornecedor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadFornecedor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadFornecedor1MouseClicked(evt);
            }
        });

        cadFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/imagens/cadUsuario.png"))); // NOI18N
        cadFornecedor.setToolTipText("Abrir Cadastro de Usuário");
        cadFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadFornecedorMouseClicked(evt);
            }
        });

        jLabel1.setText("Cadastros");

        jLabel3.setText("Pesquisas");

        cadastro.setText("Cadastro");
        cadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        clienteCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clienteCadastro.setText("Cliente");
        clienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCadastroActionPerformed(evt);
            }
        });
        cadastro.add(clienteCadastro);

        UsuarioCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UsuarioCadastro.setText("Usuário");
        UsuarioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioCadastroActionPerformed(evt);
            }
        });
        cadastro.add(UsuarioCadastro);

        FornecedorCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FornecedorCadastro.setText("Fornecedor");
        FornecedorCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FornecedorCadastroActionPerformed(evt);
            }
        });
        cadastro.add(FornecedorCadastro);

        menuBarra.add(cadastro);

        pesquisa.setText("Pesquisa");
        pesquisa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        clientePesquisado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientePesquisado.setText("Cliente");
        clientePesquisado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientePesquisadoActionPerformed(evt);
            }
        });
        pesquisa.add(clientePesquisado);

        usuarioPesquisado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usuarioPesquisado.setText("Usuário");
        usuarioPesquisado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioPesquisadoActionPerformed(evt);
            }
        });
        pesquisa.add(usuarioPesquisado);

        fornecedorPesquisado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fornecedorPesquisado.setText("Fornecedor");
        fornecedorPesquisado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorPesquisadoActionPerformed(evt);
            }
        });
        pesquisa.add(fornecedorPesquisado);

        menuBarra.add(pesquisa);

        pedido.setText("Pedido");
        pedido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoActionPerformed(evt);
            }
        });
        menuBarra.add(pedido);

        varSair.setText("Sair");
        varSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        varSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                varSairMouseClicked(evt);
            }
        });
        menuBarra.add(varSair);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrar)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(272, 272, 272)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadFornecedor1)
                            .addComponent(pesFornecedor))
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadFornecedor)
                            .addComponent(pesUsuario))
                        .addGap(0, 167, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadCliente1)
                    .addComponent(cadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadFornecedor1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pesUsuario)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pesFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void varSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_varSairMouseClicked
        int sair = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?");
        dispose();
        if (sair == 0) {
            System.exit(DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_varSairMouseClicked

    private void UsuarioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioCadastroActionPerformed
        new UsuarioCadastro().setVisible(true);
    }//GEN-LAST:event_UsuarioCadastroActionPerformed

    private void clienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCadastroActionPerformed
        new ClienteCadastro().setVisible(true);
    }//GEN-LAST:event_clienteCadastroActionPerformed

    private void clientePesquisadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientePesquisadoActionPerformed
        new ClientePesquisado().setVisible(true);
    }//GEN-LAST:event_clientePesquisadoActionPerformed

    private void usuarioPesquisadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioPesquisadoActionPerformed
        new UsuarioPesquisado().setVisible(true);
    }//GEN-LAST:event_usuarioPesquisadoActionPerformed

    private void FornecedorCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FornecedorCadastroActionPerformed
        new FornecedorCadastro().setVisible(true);
    }//GEN-LAST:event_FornecedorCadastroActionPerformed

    private void fornecedorPesquisadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorPesquisadoActionPerformed
        new FornecedorPesquisado().setVisible(true);
    }//GEN-LAST:event_fornecedorPesquisadoActionPerformed

    private void cadFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadFornecedorMouseClicked
        new UsuarioCadastro().setVisible(true);
    }//GEN-LAST:event_cadFornecedorMouseClicked

    private void cadFornecedor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadFornecedor1MouseClicked
        new FornecedorCadastro().setVisible(true);
    }//GEN-LAST:event_cadFornecedor1MouseClicked

    private void cadCliente1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadCliente1MouseClicked
        new ClienteCadastro().setVisible(true);
    }//GEN-LAST:event_cadCliente1MouseClicked

    private void pesClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesClienteMouseClicked
       new ClientePesquisado().setVisible(true);
    }//GEN-LAST:event_pesClienteMouseClicked

    private void pesFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesFornecedorMouseClicked
       new FornecedorPesquisado().setVisible(true);
    }//GEN-LAST:event_pesFornecedorMouseClicked

    private void pesUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesUsuarioMouseClicked
        new UsuarioPesquisado().setVisible(true);
    }//GEN-LAST:event_pesUsuarioMouseClicked

    private void pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoActionPerformed
       
    }//GEN-LAST:event_pedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FornecedorCadastro;
    private javax.swing.JMenuItem UsuarioCadastro;
    private javax.swing.JLabel cadCliente1;
    private javax.swing.JLabel cadFornecedor;
    private javax.swing.JLabel cadFornecedor1;
    private javax.swing.JLabel cadastrar;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenuItem clienteCadastro;
    private javax.swing.JMenuItem clientePesquisado;
    private javax.swing.JMenuItem fornecedorPesquisado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenu pedido;
    private javax.swing.JLabel pesCliente;
    private javax.swing.JLabel pesFornecedor;
    private javax.swing.JLabel pesUsuario;
    private javax.swing.JMenu pesquisa;
    private javax.swing.JLabel pesquisar;
    private javax.swing.JLabel pizza;
    private javax.swing.JLabel titulo;
    private javax.swing.JMenuItem usuarioPesquisado;
    private javax.swing.JMenu varSair;
    // End of variables declaration//GEN-END:variables
}
