/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pizzaria.tela;


import br.com.pizzaria.entidade.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author marcello.nunes
 */
public class Principal extends javax.swing.JFrame {

    private Usuario usuarioLogado;
    
    public Principal() {
        initComponents();
    }
    
    public Principal(Usuario usuario) {
        initComponents();
        usuarioLogado = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        titulo = new javax.swing.JLabel();
        menuBarra = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        clienteCadastro = new javax.swing.JMenuItem();
        usuarioCadastrado = new javax.swing.JMenuItem();
        Pesquisa = new javax.swing.JMenu();
        clientePesquisado = new javax.swing.JMenuItem();
        ajuda = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("La Louca Pizza");

        cadastro.setText("Cadastro");

        clienteCadastro.setText("Cliente");
        clienteCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCadastroActionPerformed(evt);
            }
        });
        cadastro.add(clienteCadastro);

        usuarioCadastrado.setText("Usuário");
        usuarioCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCadastradoActionPerformed(evt);
            }
        });
        cadastro.add(usuarioCadastrado);

        menuBarra.add(cadastro);

        Pesquisa.setText("Pesquisa");

        clientePesquisado.setText("Cliente");
        clientePesquisado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientePesquisadoActionPerformed(evt);
            }
        });
        Pesquisa.add(clientePesquisado);

        menuBarra.add(Pesquisa);

        ajuda.setText("Pedido");
        menuBarra.add(ajuda);

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        menuBarra.add(sair);

        setJMenuBar(menuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        int sair = JOptionPane.showConfirmDialog(null,
                "Deseja realmente sair?");
        if (sair == 0) {
            System.exit(DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_sairMouseClicked

    private void usuarioCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCadastradoActionPerformed
        
    }//GEN-LAST:event_usuarioCadastradoActionPerformed

    private void clienteCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCadastroActionPerformed
         new ClienteCadastro().setVisible(true);
    }//GEN-LAST:event_clienteCadastroActionPerformed

    private void clientePesquisadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientePesquisadoActionPerformed
         new ClientePesquisado().setVisible(true);
    }//GEN-LAST:event_clientePesquisadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Pesquisa;
    private javax.swing.JMenu ajuda;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenuItem clienteCadastro;
    private javax.swing.JMenuItem clientePesquisado;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar menuBarra;
    private javax.swing.JMenu sair;
    private javax.swing.JLabel titulo;
    private javax.swing.JMenuItem usuarioCadastrado;
    // End of variables declaration//GEN-END:variables
}
